server:
  port: 6061

spring:
  application:
    name: CONFIG-SERVICE
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/

# this configuration is for config microservices rather then other microservice
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #for localhost
      #defaultZone: http://localhost:8761/eureka/
      #for docker
      defaultZone: http://registry-container:8761/eureka/