#db configuration
spring:
  collegedatasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # for local testing
    #jdbc-url: jdbc:mysql://localhost:3306/college_db
    # to test on docker
    jdbc-url: jdbc:mysql://host.docker.internal:3306/college_db # once it deployed on docker
    username: root
    password: fubeus@123

  studentdatasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # for local testing
    #jdbc-url: jdbc:mysql://localhost:3306/student_db
    # to test on docker
    jdbc-url: jdbc:mysql://host.docker.internal:3306/student_db # once it deployed on docker
    username: root
    password: fubeus@123


# this configuration is for other microservices rather then config microservice
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #for localhost
      #defaultZone: http://localhost:8761/eureka/
      #for docker
      defaultZone: http://registry-container:8761/eureka/